// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiGMlioEB3u7Pk_Tp2exXaM1pgYkGeVL0',
    appId: '1:825399462479:web:68810e0c8cf656eb54b83a',
    messagingSenderId: '825399462479',
    projectId: 'election-37353',
    authDomain: 'election-37353.firebaseapp.com',
    storageBucket: 'election-37353.appspot.com',
    measurementId: 'G-EYTT0HK0SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB2stfJjm9o3hUWXCxRpzPwNEklIoMxUE',
    appId: '1:825399462479:android:4c45b1e91fac3b8d54b83a',
    messagingSenderId: '825399462479',
    projectId: 'election-37353',
    storageBucket: 'election-37353.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_JzsUDpDXFrS8c-Y30yNYLJ6n7AMYeGQ',
    appId: '1:825399462479:ios:c19de08b96bbc37854b83a',
    messagingSenderId: '825399462479',
    projectId: 'election-37353',
    storageBucket: 'election-37353.appspot.com',
    iosBundleId: 'com.example.vote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_JzsUDpDXFrS8c-Y30yNYLJ6n7AMYeGQ',
    appId: '1:825399462479:ios:cf64276714dd19d454b83a',
    messagingSenderId: '825399462479',
    projectId: 'election-37353',
    storageBucket: 'election-37353.appspot.com',
    iosBundleId: 'com.example.vote.RunnerTests',
  );
}
